display_name: Boinc
subdomain: boinc
routing: traefik
auto_update_default: true
containers:
  boinc:
    image_url: lscr.io/linuxserver/boinc
    image_tag: latest
    ports:
    - 8080:8080
    - 8181:8181
    volumes:
    - ${CONFIG_ROOT}/Boinc/config:/config
    service_port: '8080'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
