display_name: Pcsx2
subdomain: pcsx2
routing: traefik
auto_update_default: true
containers:
  pcsx2:
    image_url: lscr.io/linuxserver/pcsx2
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Pcsx2/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
