display_name: Retroarch
subdomain: retroarch
routing: traefik
auto_update_default: true
containers:
  retroarch:
    image_url: lscr.io/linuxserver/retroarch
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Retroarch/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
