display_name: Webstation
subdomain: webstation
routing: traefik
auto_update_default: true
containers:
  webstation:
    image_url: lscr.io/linuxserver/webstation
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Webstation/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
