display_name: Thunderbird
subdomain: thunderbird
routing: traefik
auto_update_default: true
containers:
  thunderbird:
    image_url: lscr.io/linuxserver/thunderbird
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Thunderbird/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
