display_name: Shadps4
subdomain: shadps4
routing: traefik
auto_update_default: true
containers:
  shadps4:
    image_url: lscr.io/linuxserver/shadps4
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Shadps4/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
