display_name: Firefox
subdomain: firefox
routing: traefik
auto_update_default: true
containers:
  firefox:
    image_url: lscr.io/linuxserver/firefox
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Firefox/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
