display_name: Digikam
subdomain: digikam
routing: traefik
auto_update_default: true
containers:
  digikam:
    image_url: lscr.io/linuxserver/digikam
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Digikam/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
