display_name: Limnoria
subdomain: limnoria
routing: traefik
auto_update_default: true
containers:
  limnoria:
    image_url: lscr.io/linuxserver/limnoria
    image_tag: latest
    ports:
    - 8080:8080
    volumes:
    - ${CONFIG_ROOT}/Limnoria/config:/config
    service_port: '8080'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
