display_name: Nginx
subdomain: nginx
routing: traefik
auto_update_default: true
containers:
  nginx:
    image_url: lscr.io/linuxserver/nginx
    image_tag: latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - ${CONFIG_ROOT}/Nginx/config:/config
    service_port: '80'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
