display_name: Blender
subdomain: blender
routing: traefik
auto_update_default: true
containers:
  blender:
    image_url: lscr.io/linuxserver/blender
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Blender/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
