display_name: Xemu
subdomain: xemu
routing: traefik
auto_update_default: true
containers:
  xemu:
    image_url: lscr.io/linuxserver/xemu
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Xemu/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
