display_name: Joplin
subdomain: joplin
routing: traefik
auto_update_default: true
containers:
  joplin:
    image_url: lscr.io/linuxserver/joplin
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Joplin/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
