display_name: Pycharm
subdomain: pycharm
routing: traefik
auto_update_default: true
containers:
  pycharm:
    image_url: lscr.io/linuxserver/pycharm
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Pycharm/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
