display_name: Doublecommander
subdomain: doublecommander
routing: traefik
auto_update_default: true
containers:
  doublecommander:
    image_url: lscr.io/linuxserver/doublecommander
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Doublecommander/config:/config
    - ${STORAGE_ROOT}/data:/data
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
