display_name: Rpcs3
subdomain: rpcs3
routing: traefik
auto_update_default: true
containers:
  rpcs3:
    image_url: lscr.io/linuxserver/rpcs3
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Rpcs3/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
