display_name: Orcaslicer
subdomain: orcaslicer
routing: traefik
auto_update_default: true
containers:
  orcaslicer:
    image_url: lscr.io/linuxserver/orcaslicer
    image_tag: latest
    ports:
    - 3000:3000
    - 3001:3001
    volumes:
    - ${CONFIG_ROOT}/Orcaslicer/config:/config
    service_port: '3000'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
variants_supported:
- web
- websecure
- wildcard
